channels:
- conda-forge
dependencies:
- python=3.7
- tensorflow # Must list before keras to preempt default keras backend
- bokeh
- cython
- future
- h5py
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy==1.16
- opencv
- peakutils
- pims
- scipy
- scikit-image
- scikit-learn
- spyder
- tifffile
- tqdm
